## Display
This notebook wants to discuss the mechanism of Jupyter's displaying ndarrays as cell outputs. In some cases it refuses to print all the rows, and we want to know what triggers the abbreviation.

In [1]:
import numpy as np

In [2]:
shape = (1000, 3)
A = np.arange(np.product(shape)).reshape(shape)
A

array([[   0,    1,    2],
       [   3,    4,    5],
       [   6,    7,    8],
       ...,
       [2991, 2992, 2993],
       [2994, 2995, 2996],
       [2997, 2998, 2999]])

In [7]:
A[600:]

array([[1800, 1801, 1802],
       [1803, 1804, 1805],
       [1806, 1807, 1808],
       ...,
       [2991, 2992, 2993],
       [2994, 2995, 2996],
       [2997, 2998, 2999]])

In [8]:
A[700:]

array([[2100, 2101, 2102],
       [2103, 2104, 2105],
       [2106, 2107, 2108],
       [2109, 2110, 2111],
       [2112, 2113, 2114],
       [2115, 2116, 2117],
       [2118, 2119, 2120],
       [2121, 2122, 2123],
       [2124, 2125, 2126],
       [2127, 2128, 2129],
       [2130, 2131, 2132],
       [2133, 2134, 2135],
       [2136, 2137, 2138],
       [2139, 2140, 2141],
       [2142, 2143, 2144],
       [2145, 2146, 2147],
       [2148, 2149, 2150],
       [2151, 2152, 2153],
       [2154, 2155, 2156],
       [2157, 2158, 2159],
       [2160, 2161, 2162],
       [2163, 2164, 2165],
       [2166, 2167, 2168],
       [2169, 2170, 2171],
       [2172, 2173, 2174],
       [2175, 2176, 2177],
       [2178, 2179, 2180],
       [2181, 2182, 2183],
       [2184, 2185, 2186],
       [2187, 2188, 2189],
       [2190, 2191, 2192],
       [2193, 2194, 2195],
       [2196, 2197, 2198],
       [2199, 2200, 2201],
       [2202, 2203, 2204],
       [2205, 2206, 2207],
       [2208, 2209, 2210],
 

My previous experience tells me that Jupyter can only show fully upto `333` rows. Let's verify this.

In [17]:
A[-334:]

array([[1998, 1999, 2000],
       [2001, 2002, 2003],
       [2004, 2005, 2006],
       ...,
       [2991, 2992, 2993],
       [2994, 2995, 2996],
       [2997, 2998, 2999]])

In [18]:
A[-333:]

array([[2001, 2002, 2003],
       [2004, 2005, 2006],
       [2007, 2008, 2009],
       [2010, 2011, 2012],
       [2013, 2014, 2015],
       [2016, 2017, 2018],
       [2019, 2020, 2021],
       [2022, 2023, 2024],
       [2025, 2026, 2027],
       [2028, 2029, 2030],
       [2031, 2032, 2033],
       [2034, 2035, 2036],
       [2037, 2038, 2039],
       [2040, 2041, 2042],
       [2043, 2044, 2045],
       [2046, 2047, 2048],
       [2049, 2050, 2051],
       [2052, 2053, 2054],
       [2055, 2056, 2057],
       [2058, 2059, 2060],
       [2061, 2062, 2063],
       [2064, 2065, 2066],
       [2067, 2068, 2069],
       [2070, 2071, 2072],
       [2073, 2074, 2075],
       [2076, 2077, 2078],
       [2079, 2080, 2081],
       [2082, 2083, 2084],
       [2085, 2086, 2087],
       [2088, 2089, 2090],
       [2091, 2092, 2093],
       [2094, 2095, 2096],
       [2097, 2098, 2099],
       [2100, 2101, 2102],
       [2103, 2104, 2105],
       [2106, 2107, 2108],
       [2109, 2110, 2111],
 

In [20]:
start = 137
A[start: start+334]

array([[ 411,  412,  413],
       [ 414,  415,  416],
       [ 417,  418,  419],
       ...,
       [1404, 1405, 1406],
       [1407, 1408, 1409],
       [1410, 1411, 1412]])

In [21]:
A[start: start+333]

array([[ 411,  412,  413],
       [ 414,  415,  416],
       [ 417,  418,  419],
       [ 420,  421,  422],
       [ 423,  424,  425],
       [ 426,  427,  428],
       [ 429,  430,  431],
       [ 432,  433,  434],
       [ 435,  436,  437],
       [ 438,  439,  440],
       [ 441,  442,  443],
       [ 444,  445,  446],
       [ 447,  448,  449],
       [ 450,  451,  452],
       [ 453,  454,  455],
       [ 456,  457,  458],
       [ 459,  460,  461],
       [ 462,  463,  464],
       [ 465,  466,  467],
       [ 468,  469,  470],
       [ 471,  472,  473],
       [ 474,  475,  476],
       [ 477,  478,  479],
       [ 480,  481,  482],
       [ 483,  484,  485],
       [ 486,  487,  488],
       [ 489,  490,  491],
       [ 492,  493,  494],
       [ 495,  496,  497],
       [ 498,  499,  500],
       [ 501,  502,  503],
       [ 504,  505,  506],
       [ 507,  508,  509],
       [ 510,  511,  512],
       [ 513,  514,  515],
       [ 516,  517,  518],
       [ 519,  520,  521],
 