This notebook is to make an experiment on
> Whether the computation of matrix operations will stay in the land of `np.int32` when each involved matrix has `dtype=np.int32`

In [1]:
import numpy as np

In [2]:
theta = np.pi/2
theta

1.5707963267948966

In [3]:
## 2**31 is comfortably sufficient to cover image (h, w)
## i.e. h, w < 2**31
A = np.array([
    [np.cos(theta), -np.sin(theta)],
    [np.sin(theta), np.cos(theta)]],
    dtype=np.int32)
A

array([[ 0, -1],
       [ 1,  0]], dtype=int32)

In [4]:
for theta in [k*(np.pi/2) for k in range(1,4)]:
    print(f"theta = {theta}")
    A = np.array([
        [np.cos(theta), -np.sin(theta)],
        [np.sin(theta), np.cos(theta)]],
        dtype=np.int32)
    print(f"A =\n{A}\n")

theta = 1.5707963267948966
A =
[[ 0 -1]
 [ 1  0]]

theta = 3.141592653589793
A =
[[-1  0]
 [ 0 -1]]

theta = 4.71238898038469
A =
[[ 0  1]
 [-1  0]]



In [5]:
A

array([[ 0,  1],
       [-1,  0]], dtype=int32)

In [6]:
x = np.random.randint(low=0, high=10, size=(2,1), dtype=np.int32)
x, x.dtype

(array([[4],
        [5]], dtype=int32), dtype('int32'))

In [7]:
A @ x

array([[ 5],
       [-4]], dtype=int32)

By default, when the entries in an `np.array()` are specified using Python integers, the ndarray's `dtype` will default to `int64`.

In [8]:
np.array([10, 0]).dtype

dtype('int64')

Of course you can specify otherwise.

In [9]:
np.array([10, 0], dtype=np.uint8).dtype

dtype('uint8')