In [9]:
import numpy as np
## Markov transition matrix 
P = np.array([
    [0.8054, 0.4163, 0.2285, 0.1372],
    [0.1489, 0.423 , 0.3458, 0.2147],
    [0.0266, 0.0992, 0.2109, 0.2034],
    [0.0191, 0.0615, 0.2148, 0.4447]])

In [10]:
I = np.eye(4)

In [11]:
A = P - I

In [12]:
p1 = np.array([0.2306, 0.0691, 0.0738, 0.6265])

In [13]:
np.sum(p1)

0.9999999999999999

In [29]:
P @ p1 - p1

array([ 0.08671067,  0.15449523,  0.0821832 , -0.3233891 ])

In [19]:
A @ p1

array([ 0.08671067,  0.15449523,  0.0821832 , -0.3233891 ])

In [20]:
## Why is this 0?
np.sum(_)

0.0

In [21]:
from scipy.linalg import null_space
x = null_space(A)
x

array([[-0.9278688 ],
       [-0.34149571],
       [-0.10239269],
       [-0.10934311]])

In [22]:
(p1[0]/x[0,0]) * x

array([[0.2306    ],
       [0.08487074],
       [0.0254473 ],
       [0.02717466]])

In [23]:
p1

array([0.2306, 0.0691, 0.0738, 0.6265])

In [28]:
A @ x

array([[ 8.32667268e-17],
       [-9.71445147e-17],
       [-4.16333634e-17],
       [ 3.46944695e-17]])

In [25]:
P @ x - x

array([[ 1.11022302e-16],
       [-5.55111512e-17],
       [-4.16333634e-17],
       [ 4.16333634e-17]])

In [26]:
B = np.r_[
    [[1,1,1,1]],
    np.zeros((3,4))
]
B

array([[1., 1., 1., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
# expect to have three vectors in this null space
null_space(B)

array([[ 0.        ,  0.        ,  0.8660254 ],
       [-0.57735027, -0.57735027, -0.28867513],
       [ 0.78867513, -0.21132487, -0.28867513],
       [-0.21132487,  0.78867513, -0.28867513]])